services:
  handy:
    image: "registry.robotics-lab.ru/handy:0.7.3"
    container_name: "${CONTAINER_NAME:-handy-${USER}}"
    networks: [default]
    privileged: true
    ports:
      - "${FOXGLOVE_PORT:-8765}:8765"
    volumes:
      - "/home/bakind/handy:/handy"
      - "/dev:/dev"
    deploy:
      resources:
        limits:
          memory: 40gb
        reservations:
          memory: 20gb

    build:
      dockerfile: Dockerfile
      context: .
      x-bake:
        platforms:
          - linux/arm64
          - linux/amd64
        cache-from:
          - type=registry,ref=registry.robotics-lab.ru/handy:cache-arm64
          - type=registry,ref=registry.robotics-lab.ru/handy:cache-amd64
        cache-to:
          # [!!!] Warning: https://github.com/docker/buildx/discussions/1382
          # - type=registry,mode=max,ref=registry.robotics-lab.ru/handy:cache-arm64
          # - type=registry,mode=max,ref=registry.robotics-lab.ru/handy:cache-amd64

networks:
  default:
    name: "${CONTAINER_NAME:-handy-${USER}}"
